name: Lint Helm Charts

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'nextcloud-aio-helm-chart/**'

jobs:
  lint-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4
        with:
          version: v3.11.1

      - name: Lint charts
        run: helm lint nextcloud-aio-helm-chart
